[build]
  publish = "dist" # Replace with your actual output directory
  command = "pnpm run build" # Replace with your actual build command

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
